# Generated by Django 2.0.4 on 2018-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Password'),
        ),
    ]
